### PR TITLE
AppImage: use up-to-date build-appimage action

### PR DESCRIPTION
**Pull request by v1993**

### CODE REVIEW

**Comment by v1993** [comment]
```
RuntimeError: Unable to determine the bundle architecture
```

@git-developer Any idea where this may be coming from?

**Comment by git-developer** [comment]
No. I can reproduce this error building locally with docker image `1.1.0`. It does not occur with `0.9.1`.
Could be related to  https://github.com/AppImageCrafters/appimage-builder/issues/164 and https://github.com/AppImageCrafters/appimage-builder/issues/173.

**Comment by v1993** [comment]
The second issue seems to happen with 0.9.1, though. The first has no info about its resolution and is older than the second one. I'm out of ideas here...

**Comment by git-developer** [comment]
I got an idea. The paths have changed. I'm currently fiddling, will report back.

**Comment by git-developer** [comment]
In the original image (`0.8.6` I think), files were expected the working directory. In `v1.1.0`, files are expected in the `${TARGET_APPDIR}`. Fixed in https://github.com/v1993/evdevhook2/pull/8.

**Comment by git-developer** [comment]
Additionally, `appimage-builder` calls `mksquashfs` which is not part of the `appimage-builder` image.

**Pull request merged**
